# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build projects

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: i18n
      env:
        TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
      run: |
        pip install PyYAML requests transifex-python
        python extract_translations.py
    - name: Build
      env:
        TRAVIS_CI_OPERATOR: "1"
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
        GITHUB_TOKEN: ${{ secrets.K8S_GITHUB_TOKEN }}
      run: |
        ./ci.sh install
        ./ci.sh script
        ./ci.sh deploy
        ./ci.sh bump
